Add contacts, missing handle for after adding
borkinc/BorkGUI pull request #12
Opened 2019-04-15 23:27 UTC by javierbustillo

2019-04-16 18:01 UTC, ChristianPerez34 requested changes
Having material them is overkill and could potentially mess CSS.

2019-04-16 18:01 UTC, ChristianPerez34 commented on src/js/components/ChatNavItems.jsx
> +import { withSnackbar } from 'notistack';
Remove, this is for material theme

2019-04-16 18:01 UTC, ChristianPerez34 commented on src/js/components/ChatNavItems.jsx
> +            this.props.enqueueSnackbar('Added Contact');
Snackbar is an extension for material theme. We can use [Alerts](https://reactstrap.github.io/components/alerts/) instead.
![Screenshot_2019-04-16 reactstrap - Alerts(1)](https://user-images.githubusercontent.com/22486123/56232170-21112c80-604e-11e9-86c0-2268b500f507.png)

2019-04-16 18:01 UTC, ChristianPerez34 commented on src/js/components/ChatNavItems.jsx
> +                    <Modal isOpen={this.props.added} className={this.props.className}>
```html
<UncontrolledAlert color="success">
      I am an alert and I can be dismissed!
    </UncontrolledAlert>
  );
```

2019-04-16 18:01 UTC, ChristianPerez34 commented on src/js/reducers/chat-reducer.js
> +            if(action.payload === undefined){
El payload puede llegar undefined??

2019-04-16 18:01 UTC, ChristianPerez34 commented on yarn.lock
> +"@material-ui/core@^3.9.3":
Overkill having reactstrap and material for this project. We should stick to reactstrap since its the library that used the most in our project

2019-04-16 20:53 UTC, javierbustillo commented on src/js/reducers/chat-reducer.js
> +            if(action.payload === undefined){
Yeah, un caso en que si

2019-04-16 20:56 UTC, javierbustillo commented on src/js/components/ChatNavItems.jsx
> +import { withSnackbar } from 'notistack';
this... is weird I don't have this in my branch. I removed it

2019-04-16 21:02 UTC, javierbustillo commented on src/js/components/ChatNavItems.jsx
> +                    <Modal isOpen={this.props.added} className={this.props.className}>
I'm not gonna change it, it works. Afterwards podemos cambiarlos if there is time

2019-04-17 01:32 UTC, ChristianPerez34 commented on src/js/components/ChatNavItems.jsx
> +                    <Modal isOpen={this.props.added} className={this.props.className}>
Esto era porque el que estaba utilizaba material theme

2019-04-17 01:34 UTC, ChristianPerez34 commented on src/js/reducers/chat-reducer.js
> +            if(action.payload === undefined){
Y ese caso cual es??

2019-04-17 01:46 UTC, ChristianPerez34 requested changes
yarn remove material theme package

2019-04-17 01:46 UTC, ChristianPerez34 commented on yarn.lock
> +"@material-ui/core@^3.9.3":
yarn remove this package

2019-04-17 01:50 UTC, ChristianPerez34 approved these changes

2019-04-17 01:50 UTC, ChristianPerez34 approved these changes

2019-04-17 01:50 UTC, merged